# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from redisimport import redisimport_pb2 as redisimport_dot_redisimport__pb2


class RedisImportStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Import = channel.unary_unary(
                '/redisimport.RedisImport/Import',
                request_serializer=redisimport_dot_redisimport__pb2.User.SerializeToString,
                response_deserializer=redisimport_dot_redisimport__pb2.ImportReply.FromString,
                )
        self.ImportBulk = channel.stream_unary(
                '/redisimport.RedisImport/ImportBulk',
                request_serializer=redisimport_dot_redisimport__pb2.User.SerializeToString,
                response_deserializer=redisimport_dot_redisimport__pb2.ImportReply.FromString,
                )


class RedisImportServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Import(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportBulk(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RedisImportServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Import': grpc.unary_unary_rpc_method_handler(
                    servicer.Import,
                    request_deserializer=redisimport_dot_redisimport__pb2.User.FromString,
                    response_serializer=redisimport_dot_redisimport__pb2.ImportReply.SerializeToString,
            ),
            'ImportBulk': grpc.stream_unary_rpc_method_handler(
                    servicer.ImportBulk,
                    request_deserializer=redisimport_dot_redisimport__pb2.User.FromString,
                    response_serializer=redisimport_dot_redisimport__pb2.ImportReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'redisimport.RedisImport', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RedisImport(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Import(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/redisimport.RedisImport/Import',
            redisimport_dot_redisimport__pb2.User.SerializeToString,
            redisimport_dot_redisimport__pb2.ImportReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ImportBulk(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/redisimport.RedisImport/ImportBulk',
            redisimport_dot_redisimport__pb2.User.SerializeToString,
            redisimport_dot_redisimport__pb2.ImportReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
